### ISSUE TITLE
tutanota.com domains

### ISSUE THREAD

**Issue by nikos-glikis** [disposable/disposable#141]
The below emails are hosted by tutanota.com. They have a free version but are not considered disposable:

tutanota.com
keemail.me
tuta.io

Thanks

**Comment by smeinecke** [comment]
Thank you for your ticket. I have just checked the domains in https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_source_map.txt to list the source of the domains you wrote.

The domains are imported from the list https://github.com/wesbos/burner-email-providers. Could you please open a ticket there as well so that the domains are removed from the source list? :)

I will still put the domains on our whitelist so that they are filtered.

Thanks!

**Comment by smeinecke** [comment]
They got blocked there by https://github.com/wesbos/burner-email-providers/issues/414 / https://github.com/wesbos/burner-email-providers/pull/418 - so, same problem as in #136

**Comment by nikos-glikis** [comment]
Hello,

I opened a case there too. Thanks
