### ISSUE TITLE
Please remove ProtonMail domains from GreyList

### ISSUE THREAD

**Issue by ghost** [disposable/disposable#144]
Hi!

Please remove ProtonMail domains from [GreyList](https://github.com/disposable/disposable/blob/master/greylist.txt). Yes, they provide anonymous registration, but outlook (from Microsoft evil corp) provides anonymous registration too!

Here is a proof:

https://github.com/disposable/disposable/assets/152306456/0834a69a-5944-4262-9349-3853e1852eff

You can simply create disposable mail account on outlook. So… Why blocking Proton but not Outlook?

**Comment by Hchgughcyfyg** [comment]
https://github.com/disposable/disposable/issues/144#issue-2014721129 `protonmail.com` domain missed

**Comment by smeinecke** [comment]
First of all I would like to point out that this is not a commercial list and that I maintain this project in my spare time. So it is rather counterproductive if you send me **200 Spam emails** from random addresses to my company email address with the info to remove the host again. Please behave decently and refrain from such attacks. Otherwise you will end up with users of protonmail / tutanota being seen as troublemakers.

Furthermore, I would like to point out that the "strict" list has so far been used by NOBODY and therefore your complaints are rather insignificant. I see the access numbers to the list in Github and so far it has not been accessed except manually by some individual requests through web browsers. 

I see that the domain has been removed from the original list that started the topic. I will check this in the course of this week and read the entire history and then remove the domains again accordingly.

**As I said: please behave decently and don't annoy people who don't get any money for this work - the only thing you will achieve is that either you will be banned or, out of frustration, the whole project will be set to readonly.**

**Comment by smeinecke** [comment]
> @smeinecke
> 
> Thank you for your reply and your time!
> 
> I am new here, so can I post my opinion?
> 
> > So it is rather counterproductive if you send me 200 Spam emails from random addresses
> 
> What do you mean? Who exactly?

I don't know, but there must be someone monitoring this thread/repository and sending them again today:

![grafik](https://github.com/disposable/disposable/assets/7316652/c7b55285-b3c9-4938-9312-b6b15468eeef)

> 
> > used by NOBODY
> 
> That’s good to hear! But Gmail or Outlook is NOT better. They allow anonymous registration too. So it is a kinda weird situation with discriminating look. If you think Tutanota and Protonmail should be in grey list because of anonymous registration, you should definitely consider adding outlook and gmail.

I understand your problem, but I would like to see for myself before I "hastily" undo the changes. As I'm still traveling this week, I can only take a closer look at the whole issue this weekend. 

We are currently under no time pressure as the strict list is not being used by anyone and this should therefore have no impact on users of the services in question.

**Comment by Tdtcunkbhxtx** [comment]
@smeinecke i recognise this addresses.

This user created this attack https://discord.com/invite/ndp64XbtPp

He is developer of flood attack tool. In this discord server is the bot that allows to spam mails. Also there is a developer there.
