### ISSUE TITLE
a lot of dead domains?

### ISSUE THREAD

**Issue by tcurdt** [disposable/disposable#44]
I just ran through all the 51k domain blacklist and checked the MX records.
I ended up with only 9119 domains.

But it looks like your generate script also checks MX records.
I am wondering what I might be missing.

**Comment by lryong** [comment]
Has this been followed up ?

**Comment by smeinecke** [comment]
As you may noticed, there is a method to validate the MX https://github.com/disposable/disposable/blob/e6817b8176299718916498ee1aaaaa27909e3d94/.generate#L274

https://github.com/disposable/disposable/blob/e6817b8176299718916498ee1aaaaa27909e3d94/.generate#L391

which has to be enabled manually as it takes very long to verify all domains + is not possible for all users as this sends a massive amount of DNS requests to the local resolver.

**Comment by smeinecke** [comment]
I will verify if that methods still works / if its possible to optimize the code a little to speed up the process.

**Comment by tcurdt** [comment]
That does not really address the original issue. I did run a MX check - and opened this issue because of the results.

**Comment by tcurdt** [comment]
Maybe it would also be good to keep a record of when the validation was run for a particular blacklist. To know about the "freshness".

**Comment by lryong** [comment]
I think this is an issue that can be discussed, as some users may also check MX records when verifying email addresses, and old records can prevent users from sending emails to non-existent users.

**Comment by smeinecke** [comment]
so.. your problem is that many of the domains are still in the "sources" the script just combines? o_O How should I remove them there as we don't have any access to the files/lists itself? 

Only way would be like a local database/txt file which holds a cache for non-resolving MX records which has to be automatically updated.

**Comment by tcurdt** [comment]
I am not following. I opened this issue because the blacklist.txt seems awfully outdated. I was wondering why that is.

**Comment by lryong** [comment]
I am not following. It's a awesome project and it meets my  current business needs.

**Comment by smeinecke** [comment]
Oh, okay. I did not check that file. Will add a check for that and remove the dead domains. Thanks for the info! 👍

**Comment by smeinecke** [comment]
Hm.. just checked the MX check method.. yep, you're right, there seems to be a bug as I already found multiple domains without MX which are marked as valid.

In addition to that there is also the bug that not only an MX record should be checked but also an A/AAAA/CNAME record, because this is the standard fallback according to RFC - which is also used by the providers of trash disposable emails.

**Comment by smeinecke** [comment]
DNS check fixed in 628157f7a38d6dae214181346f39ce7ada1f313d 4103c72dd63c6de71b4e435115592f6cf217b1b9 and 5a5c81c291e2646f62dc6a2ab89332b2359ab36f
